PremierTable = {
    filters: {},
    competition: {
      id: 2021,
      area: { id: 2072, name: "England" },
      name: "Premier League",
      code: "PL",
      plan: "TIER_ONE",
      lastUpdated: "2022-03-20T08:58:54Z",
    },
    season: {
      id: 1490,
      startDate: "2022-08-05",
      endDate: "2023-05-28",
      currentMatchday: 24,
      winner: null,
    },
    standings: [
      {
        stage: "REGULAR_SEASON",
        type: "TOTAL",
        group: null,
        table: [
          {
            position: 1,
            team: {
              id: 65,
              name: "Manchester City FC",
              crestUrl: "https://crests.football-data.org/65.png",
            },
            playedGames: 23,
            form: null,
            won: 16,
            draw: 3,
            lost: 4,
            points: 51,
            goalsFor: 59,
            goalsAgainst: 23,
            goalDifference: 36,
          },
          {
            position: 2,
            team: {
              id: 57,
              name: "Arsenal FC",
              crestUrl: "https://crests.football-data.org/57.png",
            },
            playedGames: 22,
            form: null,
            won: 16,
            draw: 3,
            lost: 3,
            points: 51,
            goalsFor: 47,
            goalsAgainst: 21,
            goalDifference: 26,
          },
          {
            position: 3,
            team: {
              id: 66,
              name: "Manchester United FC",
              crestUrl: "https://crests.football-data.org/66.png",
            },
            playedGames: 23,
            form: null,
            won: 14,
            draw: 4,
            lost: 5,
            points: 46,
            goalsFor: 38,
            goalsAgainst: 28,
            goalDifference: 10,
          },
          {
            position: 4,
            team: {
              id: 67,
              name: "Newcastle United FC",
              crestUrl: "https://crests.football-data.org/67.png",
            },
            playedGames: 22,
            form: null,
            won: 10,
            draw: 11,
            lost: 1,
            points: 41,
            goalsFor: 35,
            goalsAgainst: 13,
            goalDifference: 22,
          },
          {
            position: 5,
            team: {
              id: 73,
              name: "Tottenham Hotspur FC",
              crestUrl: "https://crests.football-data.org/73.svg",
            },
            playedGames: 23,
            form: null,
            won: 12,
            draw: 3,
            lost: 8,
            points: 39,
            goalsFor: 42,
            goalsAgainst: 35,
            goalDifference: 7,
          },
          {
            position: 6,
            team: {
              id: 397,
              name: "Brighton & Hove Albion FC",
              crestUrl: "https://crests.football-data.org/397.svg",
            },
            playedGames: 21,
            form: null,
            won: 10,
            draw: 5,
            lost: 6,
            points: 35,
            goalsFor: 39,
            goalsAgainst: 28,
            goalDifference: 11,
          },
          {
            position: 7,
            team: {
              id: 63,
              name: "Fulham FC",
              crestUrl: "https://crests.football-data.org/63.svg",
            },
            playedGames: 23,
            form: null,
            won: 10,
            draw: 5,
            lost: 8,
            points: 35,
            goalsFor: 34,
            goalsAgainst: 30,
            goalDifference: 4,
          },
          {
            position: 8,
            team: {
              id: 402,
              name: "Brentford FC",
              crestUrl: "https://crests.football-data.org/402.png",
            },
            playedGames: 22,
            form: null,
            won: 8,
            draw: 10,
            lost: 4,
            points: 34,
            goalsFor: 36,
            goalsAgainst: 29,
            goalDifference: 7,
          },
          {
            position: 9,
            team: {
              id: 64,
              name: "Liverpool FC",
              crestUrl: "https://crests.football-data.org/64.png",
            },
            playedGames: 21,
            form: null,
            won: 9,
            draw: 5,
            lost: 7,
            points: 32,
            goalsFor: 36,
            goalsAgainst: 28,
            goalDifference: 8,
          },
          {
            position: 10,
            team: {
              id: 61,
              name: "Chelsea FC",
              crestUrl: "https://crests.football-data.org/61.png",
            },
            playedGames: 22,
            form: null,
            won: 8,
            draw: 7,
            lost: 7,
            points: 31,
            goalsFor: 23,
            goalsAgainst: 22,
            goalDifference: 1,
          },
          {
            position: 11,
            team: {
              id: 58,
              name: "Aston Villa FC",
              crestUrl: "https://crests.football-data.org/58.png",
            },
            playedGames: 22,
            form: null,
            won: 8,
            draw: 4,
            lost: 10,
            points: 28,
            goalsFor: 26,
            goalsAgainst: 34,
            goalDifference: -8,
          },
          {
            position: 12,
            team: {
              id: 354,
              name: "Crystal Palace FC",
              crestUrl: "https://crests.football-data.org/354.png",
            },
            playedGames: 22,
            form: null,
            won: 6,
            draw: 7,
            lost: 9,
            points: 25,
            goalsFor: 20,
            goalsAgainst: 30,
            goalDifference: -10,
          },
          {
            position: 13,
            team: {
              id: 338,
              name: "Leicester City FC",
              crestUrl: "https://crests.football-data.org/338.png",
            },
            playedGames: 22,
            form: null,
            won: 7,
            draw: 3,
            lost: 12,
            points: 24,
            goalsFor: 36,
            goalsAgainst: 38,
            goalDifference: -2,
          },
          {
            position: 14,
            team: {
              id: 351,
              name: "Nottingham Forest FC",
              crestUrl: "https://crests.football-data.org/351.png",
            },
            playedGames: 22,
            form: null,
            won: 6,
            draw: 6,
            lost: 10,
            points: 24,
            goalsFor: 17,
            goalsAgainst: 37,
            goalDifference: -20,
          },
          {
            position: 15,
            team: {
              id: 76,
              name: "Wolverhampton Wanderers FC",
              crestUrl: "https://crests.football-data.org/76.svg",
            },
            playedGames: 22,
            form: null,
            won: 6,
            draw: 5,
            lost: 11,
            points: 23,
            goalsFor: 17,
            goalsAgainst: 31,
            goalDifference: -14,
          },
          {
            position: 16,
            team: {
              id: 563,
              name: "West Ham United FC",
              crestUrl: "https://crests.football-data.org/563.png",
            },
            playedGames: 22,
            form: null,
            won: 5,
            draw: 5,
            lost: 12,
            points: 20,
            goalsFor: 19,
            goalsAgainst: 27,
            goalDifference: -8,
          },
          {
            position: 17,
            team: {
              id: 341,
              name: "Leeds United FC",
              crestUrl: "https://crests.football-data.org/341.png",
            },
            playedGames: 22,
            form: null,
            won: 4,
            draw: 7,
            lost: 11,
            points: 19,
            goalsFor: 28,
            goalsAgainst: 38,
            goalDifference: -10,
          },
          {
            position: 18,
            team: {
              id: 62,
              name: "Everton FC",
              crestUrl: "https://crests.football-data.org/62.png",
            },
            playedGames: 22,
            form: null,
            won: 4,
            draw: 6,
            lost: 12,
            points: 18,
            goalsFor: 16,
            goalsAgainst: 30,
            goalDifference: -14,
          },
          {
            position: 19,
            team: {
              id: 1044,
              name: "AFC Bournemouth",
              crestUrl: "https://crests.football-data.org/1044.png",
            },
            playedGames: 22,
            form: null,
            won: 4,
            draw: 6,
            lost: 12,
            points: 18,
            goalsFor: 20,
            goalsAgainst: 44,
            goalDifference: -24,
          },
          {
            position: 20,
            team: {
              id: 340,
              name: "Southampton FC",
              crestUrl: "https://crests.football-data.org/340.png",
            },
            playedGames: 22,
            form: null,
            won: 4,
            draw: 3,
            lost: 15,
            points: 15,
            goalsFor: 18,
            goalsAgainst: 40,
            goalDifference: -22,
          },
        ],
      },
    ],
  };
  